FROM node:23-alpine3.19

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json (if available) to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the backend service port
EXPOSE 5000

# Command to run the backend service
CMD ["npm", "start"]